/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class CRS_Arguments */

#ifndef _Included_CRS_Arguments
#define _Included_CRS_Arguments
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     CRS_Arguments
 * Method:    base_bc
 * Signature: (I[I[II)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_CRS_Arguments_base_1bc
  (JNIEnv *, jobject, jint, jintArray, jintArray, jint);

#ifdef __cplusplus
}
#endif
#endif
