/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class something_SomethingJarWithJNI */

#ifndef _Included_something_SomethingJarWithJNI
#define _Included_something_SomethingJarWithJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     something_SomethingJarWithJNI
 * Method:    test
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_something_SomethingJarWithJNI_test
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
