/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class somethingelse_SomethingJarWithJNI */

#ifndef _Included_somethingelse_SomethingJarWithJNI
#define _Included_somethingelse_SomethingJarWithJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     somethingelse_SomethingJarWithJNI
 * Method:    test
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_somethingelse_SomethingJarWithJNI_test
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
