/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class somethingyet_SomethingJarWithJNI */

#ifndef _Included_somethingyet_SomethingJarWithJNI
#define _Included_somethingyet_SomethingJarWithJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     somethingyet_SomethingJarWithJNI
 * Method:    test
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_somethingyet_SomethingJarWithJNI_test
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
