/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class HpcCode_HpcNative */

#ifndef _Included_HpcCode_HpcNative
#define _Included_HpcCode_HpcNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     HpcCode_HpcNative
 * Method:    base_bc
 * Signature: (I[I[II)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_HpcCode_HpcNative_base_1bc
  (JNIEnv *, jobject, jint, jintArray, jintArray, jint);

#ifdef __cplusplus
}
#endif
#endif
